Repository dimitritsampiras/olympian, pull requests merged in 2023-03, with the labels that each got.

#200 Doc vnv report nfr user test setup
  docs/VnVReport/VnVReport.tex
Labels: documentation

#204 trability matrix
  docs/VnVReport/VnVReport.tex
Labels: documentation

#202 added scenarios and appendix reflection
  docs/VnVReport/VnVReport.tex
Labels: documentation

#206 removed uncessary things and fixed indents
  docs/VnVReport/VnVReport.tex
Labels: documentation

#207 Doc vnv report user tests raw data
  docs/VnVReport/VnVReport.tex
Labels: documentation

#211 fix to formatting of user tests and reults
  docs/VnVReport/VnVReport.tex
Labels: documentation

#208 Unit testing docs
  docs/VnVReport/VnVReport.tex
Labels: documentation

#235 229-fixed bug, can no longer edit others workouts
  src/athena/src/components/navigation/ProgramNavigator.tsx
  src/athena/src/components/screens/program/Program.tsx
  src/athena/src/components/screens/program/Workout.tsx
Labels: bug

#245 233 done btn for finish program
  src/athena/src/components/providers/ApolloClientProvider.tsx
  src/athena/src/components/screens/Programs.tsx
  src/athena/src/components/screens/program/Program.tsx
Labels: bug

#246 244-bug-fix-addedBarrierToPreventOverlap
  src/athena/src/components/containers/ScreenView.tsx
Labels: bug

#249 keyboard now dismissed on creating a program
  src/athena/src/components/screens/createProgram/ProgramName.tsx
Labels: bug

#250 247 bug noprogram name
  src/athena/src/components/screens/createProgram/CreateProgram.tsx
Labels: bug

#251 Add conditional render for creating programs from home page
  src/athena/src/components/screens/Home.tsx
Labels: enhancement
